project_id = "grfyoqsbypvvuzdudtgu"

[functions.send-webhook]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.complete-registration]
verify_jwt = false

[functions.resend-welcome-email]
verify_jwt = false

[functions.get-admin-users]
verify_jwt = true

[functions.get-pending-registration]
verify_jwt = false

[functions.send-abandoned-cart-email]
verify_jwt = false

[functions.checkout-debug-log]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false
