project_id = "grfyoqsbypvvuzdudtgu"

[functions.send-webhook]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.complete-registration]
verify_jwt = false

[functions.resend-welcome-email]
verify_jwt = false

[functions.get-stripe-metrics]
verify_jwt = true

[functions.get-user-payment-details]
verify_jwt = true

[functions.get-admin-users]
verify_jwt = true

[functions.get-pending-registration]
verify_jwt = false
