// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Preferences } from '@capacitor/preferences';

const SUPABASE_URL = "https://grfyoqsbypvvuzdudtgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyZnlvcXNieXB2dnV6ZHVkdGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNTUwMzksImV4cCI6MjA3OTgzMTAzOX0.AyCDPJkuliZnr0eaUKXUG5cJhsj6ev-4bjVmcSR3umU";

// Criação de um Adapter Customizado assíncrono para o Storage Nativo
const capacitorStorage = {
  getItem: async (key: string): Promise<string | null> => {
    const { value } = await Preferences.get({ key });
    return value;
  },
  setItem: async (key: string, value: string): Promise<void> => {
    await Preferences.set({ key, value });
  },
  removeItem: async (key: string): Promise<void> => {
    await Preferences.remove({ key });
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: capacitorStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});