// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grfyoqsbypvvuzdudtgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyZnlvcXNieXB2dnV6ZHVkdGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNTUwMzksImV4cCI6MjA3OTgzMTAzOX0.AyCDPJkuliZnr0eaUKXUG5cJhsj6ev-4bjVmcSR3umU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});